<?php
use Drupal\message\Controller\MessageController;
use Drupal\message\Entity\Message;

define('DIR_MESSAGE_DATA', 'public://message/');

function message_theme()
{
    return [
        'message.layout' => [
            'variables' => [ 'data' => null ],
            'template' => 'message.layout'
        ],
    ];

}

function message_preprocess( &$variables, $hook )
{
	/*
	$user_id = MessageController::uid();
	if( $user_id  && $hook == 'page' ){
		$variables['data']['user_unread_messages'] = Message::getUnreadMessages( $user_id  );
	}
	*/
    $variables['dir_message'] = 'modules/message';

    if ( isMessagePage() ) {
        $variables['#attached']['library'][] = 'message/default';
    }
}

function isMessagePage() {
    $request = \Drupal::request();
    $uri = $request->getRequestUri();
    if ( strpos( $uri, '/message') !== FALSE ) {
        return TRUE;
    }
    else return FALSE;
}
