<?php


function message_theme()
{
    return [
        'message.layout' => [
            'variables' => [ 'data' => null ],
            'template' => 'message.layout'
        ],
    ];

}

function message_preprocess( &$variables, $hook )
{
    $variables['dir_message'] = 'modules/message';

    if ( isMessagePage() ) {
        $variables['#attached']['library'][] = 'message/default';
    }
}

function isMessagePage() {
    $request = \Drupal::request();
    $uri = $request->getRequestUri();
    if ( strpos( $uri, '/message') !== FALSE ) {
        return TRUE;
    }
    else return FALSE;
}
